create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  company text check (company is null or char_length(company) <= 150),
  email text not null check (char_length(email) <= 254),
  service text check (service is null or char_length(service) <= 120),
  message text not null check (char_length(message) between 10 and 3000),
  source text not null default 'website',
  status text not null default 'new' check (status in ('new', 'contacted', 'closed', 'spam')),
  created_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;

-- No hay políticas públicas: las inserciones se realizan únicamente desde
-- la función segura de Next.js usando la clave privada del servidor.
create index if not exists contact_requests_created_at_idx
  on public.contact_requests (created_at desc);
